//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP_Project_DHS.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QLDauGiaEntities : DbContext
    {
        public QLDauGiaEntities()
            : base("name=QLDauGiaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ChiTietDauGia> ChiTietDauGia { get; set; }
        public virtual DbSet<DanhMucLon> DanhMucLon { get; set; }
        public virtual DbSet<DanhMucNho> DanhMucNho { get; set; }
        public virtual DbSet<DauGia> DauGia { get; set; }
        public virtual DbSet<NhanXet> NhanXet { get; set; }
        public virtual DbSet<YeuThich> YeuThich { get; set; }
        public virtual DbSet<TaiKhoan> TaiKhoan { get; set; }
    }
}
