//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP_Project_DHS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietDauGia
    {
        public int ID { get; set; }
        public int ID_DauGia { get; set; }
        public Nullable<int> ID_TaiKhoanThamGiaDauGia { get; set; }
        public Nullable<decimal> GiaGanNhat { get; set; }
        public Nullable<System.DateTime> NgayThamGiaDauGiaGanNhat { get; set; }
        public Nullable<bool> BiCam { get; set; }
        public Nullable<decimal> GiaHienTaiLucDat { get; set; }
    }
}
