//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP_Project_DHS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DauGia
    {
        public int ID { get; set; }
        public string Ten { get; set; }
        public string MoTa { get; set; }
        public string MoTaDayDu { get; set; }
        public Nullable<decimal> GiaKhoiDiem { get; set; }
        public Nullable<decimal> GiaMuaNgay { get; set; }
        public Nullable<decimal> BuocNhay { get; set; }
        public Nullable<int> YeuCauDanhGia { get; set; }
        public Nullable<System.DateTime> NgayBatDau { get; set; }
        public Nullable<System.DateTime> NgayKetThuc { get; set; }
        public Nullable<bool> GiaHanTuDong { get; set; }
        public Nullable<int> ID_NguoiDauGia { get; set; }
        public Nullable<decimal> GiaCaoNhatHienTai { get; set; }
        public int ID_DanhMucNho { get; set; }
        public Nullable<int> SoLuongHinh { get; set; }
        public Nullable<int> ID_NguoiGiuGia { get; set; }
        public Nullable<bool> DanhGia { get; set; }
        public Nullable<bool> NguoiBanDanhGia { get; set; }
        public Nullable<bool> GuiMailThatBai { get; set; }
    }
}
