//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP_Project_DHS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NhanXet
    {
        public int ID { get; set; }
        public Nullable<int> ID_NguoiDanhGia { get; set; }
        public Nullable<int> ID_NguoiDuocDanhGia { get; set; }
        public Nullable<int> ID_DauGia { get; set; }
        public Nullable<bool> Like { get; set; }
        public Nullable<System.DateTime> Ngay { get; set; }
        public string LoiNhanXet { get; set; }
        public Nullable<bool> LaNguoiBan { get; set; }
    }
}
