//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP_Project_DHS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaiKhoan
    {
        public int ID { get; set; }
        public string TenDangNhap { get; set; }
        public string HoTen { get; set; }
        public string SoDienThoai { get; set; }
        public string Email { get; set; }
        public Nullable<System.DateTime> NgaySinh { get; set; }
        public string DiaChi { get; set; }
        public string MatKhau { get; set; }
        public Nullable<int> Diem { get; set; }
        public Nullable<int> DanhGiaTot { get; set; }
        public Nullable<int> DanhGiaXau { get; set; }
        public Nullable<bool> Quyen { get; set; }
        public Nullable<bool> Vip { get; set; }
        public Nullable<System.DateTime> ThoiGianXinBan { get; set; }
        public Nullable<bool> ResetPass { get; set; }
        public Nullable<bool> TonTai { get; set; }
    }
}
